O crescimento acelerado dos centros urbanos e o aumento do fluxo de veículos tornam indispensável o uso de sistemas inteligentes para o gerenciamento do tráfego urbano. Sistemas tradicionais de semáforos, baseados em intervalos fixos de tempo, não conseguem se adaptar dinamicamente às variações do fluxo de veículos, impactando negativamente a qualidade de vida da população, aumentando o consumo de combustível, elevando os níveis de poluição atmosférica e comprometendo a eficiência dos sistemas de transporte público.

As cidades inteligentes (smart cities) propõem o uso integrado de tecnologias da informação, comunicação e automação para otimizar serviços urbanos e promover sustentabilidade, segurança e eficiência operacional. Sistemas inteligentes de controle de tráfego desempenham um papel fundamental, pois permitem a adaptação em tempo real dos semáforos conforme a demanda de veículos, reduzindo tempos de espera e melhorando a fluidez do trânsito nos cruzamentos.

O presente trabalho aborda o desenvolvimento de um sistema de controle de tráfego urbano inteligente baseado em Máquinas de Turing, um modelo formal clássico da computação. Embora abstratas, as Máquinas de Turing permitem a especificação rigorosa de algoritmos e processos de decisão, garantindo corretude lógica, previsibilidade e análise formal de complexidade.  O objetivo é decidir qual avenida de um cruzamento deve receber o sinal verde, com base no número de veículos aguardando em cada via.

Ao considerar um cruzamento com três avenidas monitoradas por sensores de contagem de veículos, o sistema proposto demonstra como regras de prioridade podem ser formalizadas computacionalmente para determinar, de forma eficiente, qual via deve receber o sinal verde. Essa abordagem leva em conta princípios fundamentais das cidades inteligentes, como o uso de dados em tempo real, a automação de decisões e a busca pela otimização dos recursos urbanos.

Dessa forma, o trabalho contribui tanto para a compreensão prática da aplicação de Máquinas de Turing em problemas do mundo real quanto para a discussão de soluções computacionais voltadas à mobilidade urbana inteligente, evidenciando a relevância da computação teórica como base para o desenvolvimento de sistemas urbanos modernos e eficientes.
